# Generated by Django 3.1.5 on 2021-01-06 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingspage',
            name='page_image',
            field=models.ForeignKey(blank=True, help_text='En frivillig presentationsbild för sidan. Om ingen bild väljs så får inlägget automatiskt en standardbild.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='author',
            field=models.CharField(help_text='Här skriver du in namnet på författaren/författarna.', max_length=150, null=True),
        ),
    ]
