# Generated by Django 3.1.5 on 2021-01-06 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210106_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='published',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Här skriver jag inget för jag lägger inte in det i FieldPanel ens'),
        ),
    ]
