# Generated by Django 3.1.5 on 2021-01-08 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('blogs', '0003_auto_20210106_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='page_image',
            field=models.ForeignKey(blank=True, help_text='En frivillig bakgrundsbild för sidan. Om ingen bild väljs så får inlägget automatiskt en standardbild.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='bloglistingspage',
            name='page_image',
            field=models.ForeignKey(blank=True, help_text='En frivillig bakgrundsbild för sidan. Om ingen bild väljs så får inlägget automatiskt en standardbild.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
