# Generated by Django 3.1.5 on 2021-01-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210108_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='start_text',
            field=models.TextField(help_text='Här kan du skriva ett längre stycke text, som kommer hamna bredvid din presentationsbild.', null=True),
        ),
    ]
