# Generated by Django 3.1.5 on 2021-01-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blogpage_start_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='start_text',
            field=models.TextField(help_text="Här kan du skriva ett längre stycke text, som kommer hamna bredvid din presentationsbild. Det här texten är tänkt att vara 'starttexten' på ditt inlägg.", null=True),
        ),
    ]
