# Generated by Django 3.1.5 on 2021-01-09 11:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20210109_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='start_text',
            field=wagtail.core.fields.RichTextField(help_text="Här kan du skriva ett längre stycke text, som kommer hamna bredvid din presentationsbild. Det här texten är tänkt att vara 'starttexten' på ditt inlägg, och bör, för utseendets skull, vara max 6 rader."),
        ),
    ]
