# Generated by Django 3.1.5 on 2021-01-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_remove_boardpage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardlistingspage',
            name='subtitle',
            field=models.TextField(blank=True, help_text='En kort beskrivning av vad för typ av information man kan sätta upp på anslagstavlan', max_length=500, null=True),
        ),
    ]
